In [1]:
import nltk
nltk.download('punkt')


[nltk_data] Downloading package punkt to C:\Users\punith
[nltk_data]     yc\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [2]:
!pip install nltk

In [3]:
corpus=""" hello! welcome to youtube nlp tutorial
please do watch the entire course to master the nlp"""

In [4]:
corpus

' hello! welcome to youtube nlp tutorial\nplease do watch the entire course to master the nlp'

In [5]:
from nltk.tokenize import word_tokenize

In [6]:
word_tokenize(corpus)

['hello',
 '!',
 'welcome',
 'to',
 'youtube',
 'nlp',
 'tutorial',
 'please',
 'do',
 'watch',
 'the',
 'entire',
 'course',
 'to',
 'master',
 'the',
 'nlp']

In [7]:
from nltk.tokenize import wordpunct_tokenize

In [8]:
wordpunct_tokenize(corpus)

['hello',
 '!',
 'welcome',
 'to',
 'youtube',
 'nlp',
 'tutorial',
 'please',
 'do',
 'watch',
 'the',
 'entire',
 'course',
 'to',
 'master',
 'the',
 'nlp']

### stemming

In [9]:
words=["eating","eats","eaten","writing","writes","programming","programms","history","finally","finalize"]

### porter stemmer

In [10]:
from nltk.stem import PorterStemmer
ps=PorterStemmer()

In [11]:
for word in words:
    print(word+"-->"+ps.stem(word))

eating-->eat
eats-->eat
eaten-->eaten
writing-->write
writes-->write
programming-->program
programms-->programm
history-->histori
finally-->final
finalize-->final


In [12]:
ps.stem("congratulations")

'congratul'

In [13]:
from nltk.stem import SnowballStemmer
st=SnowballStemmer('english')

In [14]:
st.stem("goes")

'goe'

In [15]:
st.stem("congratulations")

'congratul'

In [16]:
import nltk
nltk.download('wordnet')


[nltk_data] Downloading package wordnet to C:\Users\punith
[nltk_data]     yc\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [17]:
from nltk.stem import WordNetLemmatizer
wn=WordNetLemmatizer()

In [18]:
wn.lemmatize("congratulations")

'congratulation'

In [19]:
wn.lemmatize("universal")

'universal'

In [20]:
wn.lemmatize("goes")

'go'

In [21]:
words=["eating","eats","eaten","writing","writes","programming","programms","history","finally","finalize"]

In [22]:
for word in words:
    print(word+"-->"+wn.lemmatize(word))

eating-->eating
eats-->eats
eaten-->eaten
writing-->writing
writes-->writes
programming-->programming
programms-->programms
history-->history
finally-->finally
finalize-->finalize


In [23]:
for word in words:
    print(word+"-->"+wn.lemmatize((word),pos="v"))

eating-->eat
eats-->eat
eaten-->eat
writing-->write
writes-->write
programming-->program
programms-->programms
history-->history
finally-->finally
finalize-->finalize


In [24]:
for word in words:
    print(word+"-->"+wn.lemmatize((word),pos="r"))

eating-->eating
eats-->eats
eaten-->eaten
writing-->writing
writes-->writes
programming-->programming
programms-->programms
history-->history
finally-->finally
finalize-->finalize


In [25]:
for word in words:
    print(word+"-->"+wn.lemmatize((word),pos="n"))

eating-->eating
eats-->eats
eaten-->eaten
writing-->writing
writes-->writes
programming-->programming
programms-->programms
history-->history
finally-->finally
finalize-->finalize


In [26]:
for word in words:
    print(word+"-->"+wn.lemmatize((word),pos="a"))

eating-->eating
eats-->eats
eaten-->eaten
writing-->writing
writes-->writes
programming-->programming
programms-->programms
history-->history
finally-->finally
finalize-->finalize


In [27]:
name="""he is a good boy
        she is a good girl
        boy and girl are good"""

In [28]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [29]:
from nltk.tokenize import word_tokenize

In [30]:
df=word_tokenize(name)

In [31]:
df

['he',
 'is',
 'a',
 'good',
 'boy',
 'she',
 'is',
 'a',
 'good',
 'girl',
 'boy',
 'and',
 'girl',
 'are',
 'good']

In [32]:
dim=cv.fit_transform(df)

In [33]:
cv.vocabulary_

{'he': 5,
 'is': 6,
 'good': 4,
 'boy': 2,
 'she': 7,
 'girl': 3,
 'and': 0,
 'are': 1}

In [34]:

print(dim[0].toarray())
print(dim[1].toarray())
print(dim[2].toarray())
print(dim[3].toarray())
print(dim[4].toarray())
print(dim[5].toarray())
print(dim[6].toarray())
print(dim[7].toarray())



[[0 0 0 0 0 1 0 0]]
[[0 0 0 0 0 0 1 0]]
[[0 0 0 0 0 0 0 0]]
[[0 0 0 0 1 0 0 0]]
[[0 0 1 0 0 0 0 0]]
[[0 0 0 0 0 0 0 1]]
[[0 0 0 0 0 0 1 0]]
[[0 0 0 0 0 0 0 0]]


In [35]:
import numpy as np
import pandas as pd

In [36]:
df=pd.DataFrame({'text':["people watch campusx","campusx watch campusx","people write comment","campusx write comment"],"output":[1,1,0,0]})

In [37]:
df

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [38]:
from sklearn.feature_extraction.text import CountVectorizer

In [39]:
cv=CountVectorizer()

In [40]:
df=cv.fit_transform(df['text'])

In [41]:
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}


In [42]:
print(df[0].toarray())
print(df[1].toarray())
print(df[2].toarray())
print(df[3].toarray())

[[1 0 1 1 0]]
[[2 0 0 1 0]]
[[0 1 1 0 1]]
[[1 1 0 0 1]]


In [43]:
text=["he is a good boy","she is a good girl","boy and girl are good"]

In [44]:
df1=pd.DataFrame(text,columns=["abc"])

In [45]:
from sklearn.feature_extraction.text import CountVectorizer

In [46]:
cv=CountVectorizer()

In [47]:
df1=cv.fit_transform(df1['abc'])

In [48]:
print(cv.vocabulary_)

{'he': 5, 'is': 6, 'good': 4, 'boy': 2, 'she': 7, 'girl': 3, 'and': 0, 'are': 1}


In [49]:
print(df1[0].toarray())
print(df1[1].toarray())
print(df1[2].toarray())
print(df1[3].toarray())

[[0 0 1 0 1 1 1 0]]
[[0 0 0 1 1 0 1 1]]
[[1 1 1 1 1 0 0 0]]


IndexError: row index (3) out of range

In [50]:
df

<4x5 sparse matrix of type '<class 'numpy.int64'>'
	with 11 stored elements in Compressed Sparse Row format>

In [51]:
df=pd.DataFrame({'text':["people watch campusx","campusx watch campusx","people write comment","campusx write comment"],"output":[1,1,0,0]})

In [52]:
df

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [53]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(ngram_range=(2,2))
dim=cv.fit_transform(df['text'])

In [54]:
print(cv.vocabulary_)

{'people watch': 2, 'watch campusx': 4, 'campusx watch': 0, 'people write': 3, 'write comment': 5, 'campusx write': 1}


In [55]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(ngram_range=(3,3))
dim=cv.fit_transform(df['text'])
print(cv.vocabulary_)

{'people watch campusx': 2, 'campusx watch campusx': 0, 'people write comment': 3, 'campusx write comment': 1}


In [56]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(ngram_range=(1,2))
dim=cv.fit_transform(df['text'])
print(cv.vocabulary_)

{'people': 4, 'watch': 7, 'campusx': 0, 'people watch': 5, 'watch campusx': 8, 'campusx watch': 1, 'write': 9, 'comment': 3, 'people write': 6, 'write comment': 10, 'campusx write': 2}


In [57]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(ngram_range=(1,3))
dim=cv.fit_transform(df['text'])
print(cv.vocabulary_)

{'people': 6, 'watch': 11, 'campusx': 0, 'people watch': 7, 'watch campusx': 12, 'people watch campusx': 8, 'campusx watch': 1, 'campusx watch campusx': 2, 'write': 13, 'comment': 5, 'people write': 9, 'write comment': 14, 'people write comment': 10, 'campusx write': 3, 'campusx write comment': 4}


In [74]:
df=pd.DataFrame({'text':["people watch campusx","campusx watch campusx","people write comment","campusx write comment"],"output":[1,1,0,0]})

In [75]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf=TfidfVectorizer()


In [76]:
tf.fit_transform(df['text']).toarray()

array([[0.49681612, 0.        , 0.61366674, 0.61366674, 0.        ],
       [0.8508161 , 0.        , 0.        , 0.52546357, 0.        ],
       [0.        , 0.57735027, 0.57735027, 0.        , 0.57735027],
       [0.49681612, 0.61366674, 0.        , 0.        , 0.61366674]])